name: Deploy to Azure

on: push

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"

      - name: Pulumi Stack Select
        uses: pulumi/actions@v4
        with:
          command: stack select mydostai/pulumi-python-container/dev

      - name: Pulumi up
        uses: pulumi/actions@v4
        with:
          command: up

        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
